[package]
name = "gw2timers"
version = "0.1.0"
authors = ["Ben Whitley <dev@purplg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4.19"